// <auto-generated />
using System;
using FutbolAnalizPazari.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FutbolAnalizPazari.Migrations
{
    [DbContext(typeof(AnalizPlatformuContext))]
    partial class AnalizPlatformuContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FutbolAnalizPazari.Models.AnalizKategori", b =>
                {
                    b.Property<int>("KatergoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KatergoriId"));

                    b.Property<string>("KategoriAd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KatergoriId");

                    b.ToTable("AnalizKategori");
                });

            modelBuilder.Entity("FutbolAnalizPazari.Models.AnalizciProfil", b =>
                {
                    b.Property<int>("AnalizciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnalizciId"));

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AnalizPuan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CalistigiKulup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DogumTarihi")
                        .HasColumnType("date");

                    b.Property<string>("Hakkinda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OnayAnalizSay")
                        .HasColumnType("int");

                    b.Property<string>("Sifre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YaptigiAnalizSay")
                        .HasColumnType("int");

                    b.HasKey("AnalizciId");

                    b.ToTable("AnalizciProfil", (string)null);
                });

            modelBuilder.Entity("FutbolAnalizPazari.Models.Basvurular", b =>
                {
                    b.Property<int>("BasvuruID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BasvuruID"));

                    b.Property<string>("AnalistNotu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AnalizciID")
                        .HasColumnType("int");

                    b.Property<string>("DosyaYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Durum")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Puan")
                        .HasColumnType("tinyint");

                    b.Property<int>("RaporID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("BasvuruID");

                    b.ToTable("Basvurular", (string)null);
                });

            modelBuilder.Entity("FutbolAnalizPazari.Models.Musteriler", b =>
                {
                    b.Property<int>("MusteriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusteriID"));

                    b.Property<string>("HesapDurum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriTip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seviye")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SirketAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YetkiliAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YetkiliMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YetkiliSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusteriID");

                    b.ToTable("Musteriler", (string)null);
                });

            modelBuilder.Entity("FutbolAnalizPazari.Models.Raporlar", b =>
                {
                    b.Property<int>("RaporId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RaporId"));

                    b.Property<int?>("KategoriID")
                        .HasColumnType("int");

                    b.Property<string>("MacBilgisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MusteriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SonTeslimTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("RaporId");

                    b.ToTable("Raporlar", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
